[book]
authors = ["Jason"]
language = "zh-TW"
multilingual = false
src = "src"
title = "The Embedded Rust Book"

[output.html]
default-theme = "rust"
git-repository-url = "https://shihyu.github.io/rust-embedded"
